### ISSUE TITLE
自定义端口无效

### ISSUE THREAD

**Issue by yyiwu** [Misaka-blog/naiveproxy-script#1]
我用脚本自定义naiveproxy端口为2200无法响应客户端请求，但是换成443端口就可以

**Comment by Misaka-blog** [comment]
有没有日志，看下

**Comment by Govenry** [comment]
自定义端口是46254
2023/06/22 22:29:07 127.0.0.1:8511 accepted //www.youtube.com:443 [PROXY]
[Naive] [0622/222907.539:INFO:naive_connection.cc(273)] Connection 73 to www.youtube.com:443
[Naive] [0622/222907.650:INFO:naive_proxy.cc(192)] Connection 72 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [0622/222907.867:INFO:naive_proxy.cc(192)] Connection 73 closed: ERR_PROXY_CONNECTION_FAILED
2023/06/22 22:29:08 127.0.0.1:8514 accepted //www.youtube.com:443 [PROXY]
2023/06/22 22:29:08 127.0.0.1:8515 accepted //www.youtube.com:443 [PROXY]
[Naive] [0622/222908.319:INFO:naive_connection.cc(273)] Connection 74 to www.youtube.com:443
[Naive] [0622/222908.319:INFO:naive_connection.cc(273)] Connection 75 to www.youtube.com:443
2023/06/22 22:29:08 127.0.0.1:8520 accepted //www.youtube.com:443 [PROXY]
[Naive] [0622/222908.884:INFO:naive_connection.cc(273)] Connection 76 to www.youtube.com:443
[Naive] [0622/222908.967:INFO:naive_proxy.cc(192)] Connection 71 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [0622/222909.520:INFO:naive_proxy.cc(192)] Connection 69 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [0622/222909.551:INFO:naive_proxy.cc(192)] Connection 70 closed: ERR_PROXY_CONNECTION_FAILED
2023/06/22 22:29:09 127.0.0.1:8523 accepted //beacons2.gvt2.com:443 [PROXY]
[Naive] [0622/222909.854:INFO:naive_connection.cc(273)] Connection 77 to beacons2.gvt2.com:443
[Naive] [0622/222909.879:INFO:naive_proxy.cc(192)] Connection 62 closed: ERR_PROXY_CONNECTION_FAILED
2023/06/22 22:29:10 127.0.0.1:8529 accepted //www.youtube.com:443 [PROXY]
[Naive] [0622/222910.488:INFO:naive_connection.cc(273)] Connection 78 to www.youtube.com:443
2023/06/22 22:29:10 127.0.0.1:8532 accepted //beacons2.gvt2.com:443 [PROXY]
[Naive] [0622/222910.522:INFO:naive_connection.cc(273)] Connection 79 to beacons2.gvt2.com:443
2023/06/22 22:29:10 127.0.0.1:8535 accepted //jnn-pa.googleapis.com:443 [PROXY]
[Naive] [0622/222910.553:INFO:naive_connection.cc(273)] Connection 80 to jnn-pa.googleapis.com:443
[Naive] [0622/222910.613:INFO:naive_proxy.cc(192)] Connection 78 closed: ERR_PROXY_CONNECTION_FAILED
2023/06/22 22:29:10 127.0.0.1:8539 accepted //beacons.gvt2.com:443 [PROXY]
[Naive] [0622/222910.894:INFO:naive_connection.cc(273)] Connection 81 to beacons.gvt2.com:443
[Naive] [0622/222911.264:INFO:naive_proxy.cc(192)] Connection 76 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [0622/222911.265:INFO:naive_proxy.cc(192)] Connection 75 closed: ERR_PROXY_CONNECTION_FAILED
2023/06/22 22:29:11 127.0.0.1:8543 accepted //www.youtube.com:443 [PROXY]
[Naive] [0622/222911.617:INFO:naive_connection.cc(273)] Connection 82 to www.youtube.com:443
[Naive] [0622/222911.815:INFO:naive_proxy.cc(192)] Connection 82 closed: ERR_PROXY_CONNECTION_FAILED

安装成功但是连不上

**Comment by Misaka-blog** [comment]
已修复，困扰我几个月了终于自己修好了
